### ISSUE TITLE
Create a proper readthedocs pipeline

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils-base#4]
Just in case when we want to generate a separate readthedocs for `djutils-base`, we need to comply with the new rules for reathedocs. For readthedocs, a new file called `.readthedocs.yaml` in the root directory of the project is now needed, with the following content:

```yaml
# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt
```

As can be seen on the last line, the file `requirements.txt` has been moved to the `docs` folder to minimize the number of files in the root folder.
